server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: flight
    url: jdbc:h2:~/h2db/flightbooking/flightdb;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    username: flight
  h2:
    console:
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
